baseURL: https://konafarry.com/
languageCode: en-us
title: Kona Farry
summaryLength: 20
copyright: © Kona Farry
params:
    author:
        email: kona@konafarry.com
        name: Kona Farry
outputs: 
    home: 
        - html
    section: 
        - html
        - rss
    taxonomy: 
    term: 
outputFormats: 
    rss: 
        baseName: feed